// Package contentanalysis processes committed posts independently of HTTP clients.
package contentanalysis

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"kutezh/backend/internal/contentpolicy"
	"math"
	"net/http"
	"os"
	"path/filepath"
	"strings"
	"time"
)

// Results are review signals, never a finding that a law was broken.
type Analysis struct {
	Model       string             `json:"model"`
	Version     string             `json:"version"`
	Scores      map[string]float64 `json:"scores"`
	Flags       []string           `json:"flags"`
	ReviewFlags []string           `json:"review_flags"`
	Truncated   bool               `json:"truncated"`
	Complete    *bool              `json:"complete,omitempty"`
}
type Analyzer struct {
	imageURL, textURL, mediaDir string
	client                      *http.Client
}

func NewAnalyzer(imageURL, textURL, mediaDir string) *Analyzer {
	return &Analyzer{imageURL: imageURL, textURL: textURL, mediaDir: mediaDir, client: &http.Client{Timeout: 15 * time.Second}}
}
func (a *Analyzer) request(ctx context.Context, url, contentType string, body io.Reader) (Analysis, error) {
	req, err := http.NewRequestWithContext(ctx, http.MethodPost, url, body)
	if err != nil {
		return Analysis{}, err
	}
	req.Header.Set("Content-Type", contentType)
	resp, err := a.client.Do(req)
	if err != nil {
		return Analysis{}, fmt.Errorf("inference unavailable")
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		return Analysis{}, fmt.Errorf("inference HTTP %d", resp.StatusCode)
	}
	var out Analysis
	if err = json.NewDecoder(io.LimitReader(resp.Body, 128<<10)).Decode(&out); err != nil {
		return out, fmt.Errorf("invalid inference response")
	}
	if len(out.Scores) == 0 || out.Version == "" || (out.Complete != nil && !*out.Complete) ||
		(out.Version == contentpolicy.SafetyVersion && out.Complete == nil) {
		return out, fmt.Errorf("incomplete inference response")
	}
	for _, score := range out.Scores {
		if math.IsNaN(score) || math.IsInf(score, 0) || score < 0 || score > 1 {
			return out, fmt.Errorf("invalid inference score")
		}
	}
	return out, nil
}
func (a *Analyzer) Image(ctx context.Context, key string) (Analysis, error) {
	if key == "" || filepath.Base(key) != key || key == "." || key == ".." {
		return Analysis{}, fmt.Errorf("invalid media key")
	}
	// Storage keys are immutable, generated by the upload service. OpenRoot also
	// prevents a symlink inside the media directory escaping the storage root.
	root, err := os.OpenRoot(a.mediaDir)
	if err != nil {
		return Analysis{}, fmt.Errorf("media storage unavailable")
	}
	defer root.Close()
	file, err := root.Open(key)
	if err != nil {
		return Analysis{}, fmt.Errorf("media unavailable")
	}
	defer file.Close()
	info, err := file.Stat()
	if err != nil || !info.Mode().IsRegular() || info.Size() <= 0 || info.Size() > 10<<20 {
		return Analysis{}, fmt.Errorf("invalid media size")
	}
	data, err := io.ReadAll(io.LimitReader(file, (10<<20)+1))
	if err != nil {
		return Analysis{}, fmt.Errorf("media read failed")
	}
	return a.request(ctx, a.imageURL, "application/octet-stream", bytes.NewReader(data))
}
func (a *Analyzer) Text(ctx context.Context, text string) (Analysis, error) {
	data, _ := json.Marshal(map[string]string{"text": text})
	out, err := a.request(ctx, a.textURL, "application/json", bytes.NewReader(data))
	if err != nil {
		return out, err
	}
	if !out.Truncated {
		return out, nil
	}
	// The existing text service has a token limit. Split and retry every part,
	// rather than silently declaring only the beginning of a post analyzed.
	runes := []rune(text)
	if len(runes) < 2 {
		return out, fmt.Errorf("text remains truncated")
	}
	middle := len(runes) / 2
	overlap := 0
	if len(runes) > 64 {
		overlap = 16
	}
	left, err := a.Text(ctx, string(runes[:middle+overlap]))
	if err != nil {
		return out, err
	}
	right, err := a.Text(ctx, string(runes[middle-overlap:]))
	if err != nil {
		return out, err
	}
	if left.Version != right.Version {
		return out, fmt.Errorf("text model changed during analysis")
	}
	for label, score := range right.Scores {
		if score > left.Scores[label] {
			left.Scores[label] = score
		}
	}
	left.Flags = unique(append(left.Flags, right.Flags...))
	left.ReviewFlags = unique(append(left.ReviewFlags, right.ReviewFlags...))
	left.Truncated = false
	return left, nil
}

func (a *Analyzer) HardMediaLabels(ctx context.Context, key, mimeType string, durationMS int) ([]string, error) {
	if strings.HasPrefix(mimeType, "video/") {
		frames, err := a.Video(ctx, key, durationMS)
		if err != nil {
			return nil, err
		}
		var labels []string
		for _, frame := range frames {
			labels = append(labels, imageBlockLabels(frame.Analysis)...)
		}
		return unique(labels), nil
	}
	result, err := a.Image(ctx, key)
	if err != nil {
		return nil, err
	}
	if result.Version != ImageVersion {
		return nil, fmt.Errorf("unexpected image model version")
	}
	return imageBlockLabels(result), nil
}

func unique(values []string) []string {
	seen := map[string]bool{}
	out := []string{}
	for _, s := range values {
		if s != "" && !seen[s] {
			seen[s] = true
			out = append(out, s)
		}
	}
	return out
}
func reviewLabels(a Analysis) []string {
	return unique(append(append([]string{}, a.Flags...), a.ReviewFlags...))
}
func reviewReason(labels []string) string {
	names := map[string]string{"anatomical_nudity": "обнажённые интимные части тела", "sexual_explicit": "явный сексуальный контент", "sexual_suggestive": "сексуализированный контент", "violence": "насилие", "graphic_violence": "графическая жестокость или тяжёлые травмы", "drug_visual": "возможные наркотические вещества", "extremist_symbol": "возможная экстремистская символика", "weapon": "оружие", "toxic": "токсичный текст", "insult": "оскорбления", "obscene": "ненормативная лексика", "obscenity": "ненормативная лексика", "profanity": "ненормативная лексика", "politics": "политическая тематика", "dangerous": "потенциально опасный текст", "threat": "угрозы", "identity_hate": "язык вражды"}
	out := []string{}
	for _, label := range unique(labels) {
		if name, ok := names[label]; ok {
			out = append(out, name)
		} else {
			out = append(out, "текст требует внимания")
		}
	}
	return "ИИ: требуется проверка — " + strings.Join(unique(out), ", ") + ". Это сигнал для модератора, не установленное нарушение закона."
}
